# Generated by Django 4.1 on 2022-09-06 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Evaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("github_user", models.CharField(max_length=50)),
                ("has_photo", models.BooleanField()),
                ("has_email", models.BooleanField()),
                ("has_linkedin", models.BooleanField()),
                ("has_readme", models.BooleanField()),
                ("stacks", models.IntegerField()),
                ("repositories", models.IntegerField()),
                ("pinned_repositories", models.IntegerField()),
                ("grade", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Tracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("clicks", models.IntegerField(default=0)),
            ],
        ),
    ]
