# Generated by Django 4.1 on 2022-09-11 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evaluator", "0007_groupcsv_groupevaluation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupcsv",
            name="file",
            field=models.FileField(upload_to="csvs/"),
        ),
    ]
